add: コメント関係のAPIの実装
sayasurvey/queque_board_api pull request #39
Opened 2023-07-07 04:37 UTC by sayasurvey

# 実装内容
- コメント新規投稿: コメントを新しく作成する
- コメント編集: 　　以前作成されたコメントの文章を変更する
- コメント削除: 　　idと一致するコメントを削除する

# 検証方法
以下のURLとリクエストのデータはuserId: 1, boardId:1のデータが登録されていることが前提となります
適宜userIdとboardIdの部分は自分の環境に合わせて修正してください
- コメント新規投稿
URL(POST): http://localhost:3001/api/board/1/comment/
body:
{
    "content": "comment create",
    "userId": 1
}

- コメント編集
URL(PUT): http://localhost:3001/api/board/1/comment/1
body:
{
    "content": "comment update",
    "userId": 1
}

- コメント削除
URL(DELETE): http://localhost:3001/api/board/1/comment/1

# 設計書
- コメント新規投稿
https://implcojp.sharepoint.com/:x:/s/Times/EadDqJjcEppLo6rnufc4pdMBF_2ywBXCTAf0110FOnqLpg?e=SkDeJU

- コメント編集
https://implcojp.sharepoint.com/:x:/s/Times/ETf7enAQ0JxKqQquu49RsiABp2-5vuNk1Ei7DD1I7TS7gQ?e=SeXwe5

- コメント削除
https://implcojp.sharepoint.com/:x:/s/Times/EfueXd4L0HVFpZBGAQ7iRD0BjHHB-L_7wUl5E3zPVuN6YA?e=Z2Z5hF

2023-07-08 12:40 UTC, soramar reviewed
下記リンクの内容を参考に例外処理をCommentControllerに実装
https://github.com/sayasurvey/queque_board_api/pull/39

2023-07-08 12:40 UTC, soramar commented on src/api/controller/CommentController.ts
> +      const { content, userId } = req.body;
修正 | req.bodyの分割代入はtryの外で記述

2023-07-08 12:40 UTC, soramar commented on src/api/controller/CommentController.ts
> +      const { content, userId } = req.body;
修正 | req.bodyの分割代入はtryの外で記述

2023-07-08 12:41 UTC, soramar commented
修正 | 下記リンクの内容を参考に例外処理をCommentControllerに実装
https://github.com/sayasurvey/queque_board_api/pull/39

2023-07-27 15:09 UTC, sayasurvey commented on src/api/controller/CommentController.ts
> +      const { content, userId } = req.body;
修正しました（626e6434c2e141118a82d98a96c2300a16f35617）

2023-07-27 15:52 UTC, sayasurvey commented
> 修正 | 下記リンクの内容を参考に例外処理をCommentControllerに実装 #39
修正しました(eb4c6911a627e4d5da20c1b985fe520569200b8c 029e4a1db1ea903fe15360d778a15593a91c2e0a)

2023-07-27 15:52 UTC, sayasurvey commented on src/api/controller/CommentController.ts
> +      const { content, userId } = req.body;
修正しました（626e6434c2e141118a82d98a96c2300a16f35617）

2023-07-27 16:33 UTC, sorafujitani requested changes
修正
投稿詳細（`/api/board/:id`）の取得時に、関連するコメントを同時に取得してくる設計なので、当PR内でその実装もお願いしたいです。

https://teams.microsoft.com/_?culture=ja-jp&country=jp#/apps/1c256a65-83a6-4b5c-9ccf-78f8afb6f1e8/sections/MyNotebook

2023-07-27 16:33 UTC, soramar commented on src/api/model/Comment.ts
> +    })
修正
data内のuserIdとboarIdを書く順番を統一

```
const comment = await prismaContext.comment
    .create({
      data: {
        content,
        userId,
        boardId
      }
    })
```

2023-07-30 16:04 UTC, sayasurvey commented on src/api/model/Comment.ts
> +    })
修正しました(191e76e3906d5076e0a8a619fbe63ca054a492f4)

2023-07-30 16:05 UTC, sayasurvey commented
> 修正 投稿詳細（`/api/board/:id`）の取得時に、関連するコメントを同時に取得してくる設計なので、当PR内でその実装もお願いしたいです。
> 
> https://teams.microsoft.com/_?culture=ja-jp&country=jp#/apps/1c256a65-83a6-4b5c-9ccf-78f8afb6f1e8/sections/MyNotebook

修正しました(de16174a37bf58b4847251fa13cdb78962e3c74f)

2023-07-31 00:55 UTC, soramar commented on src/api/model/Board.ts
> +        }
修正
commentはselect内でidも返却するように修正。
設計書も必要であれば修正
```
{
    "message": "this board get is success",
    "board": {
        "id": 1,
        "title": "title01",
        "content": "content01",
        "boardImage": "",
        "userId": 1,
        "user": {
            "name": "user01"
        },
        "comments": [
            {
                "id": 5,
                "content": "comment01edited",
                "user": {
                    "name": "user01"
                }
            }
        ]
    }
}
```

2023-07-31 00:55 UTC, soramar commented on src/api/model/Comment.ts
> +import { privateDecrypt } from "crypto";
修正
削除

2023-07-31 00:55 UTC, soramar commented on src/api/model/Comment.ts
> +};
修正
検証用メソッドはマージするのであれば、その旨をコメントアウトで記載。
必要なければ削除

2023-07-31 04:31 UTC, sayasurvey commented on src/api/model/Board.ts
> +        }
commentテーブルのカラム情報を全て返すように修正しました(bda7dd8d9e6142929eb519ffb7b1bbf926528696)

2023-07-31 04:31 UTC, sayasurvey commented on src/api/model/Comment.ts
> +import { privateDecrypt } from "crypto";
削除しました(3003c37f60679357ab1c1981b18b99b3b47d8664)

2023-07-31 04:32 UTC, sayasurvey commented on src/api/model/Comment.ts
> +};
不要のため削除しました(f4e1811cfae833794575992162f7391cd16e31b2)

2023-07-31 13:34 UTC, sayasurvey commented
token検証機能追加(097ff72f2200c7de0f015e74bc6a3a2a49013f30)

2023-08-01 13:34 UTC, merged